name: GitHub Actions Demo
on:
  push:
      branches: [main]
      paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Referencing branch: ${{github.ref}} from repo $${{github.repository}}"

      - uses: actions/checkout@v4

      - name: List all files in repo
        run: |
          echo "The files in the repo: $${{github.repository}} are:"
          tree
        
    
