name: 'Docker Workflow Action'
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker container action
        id: hello-docker-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@mark-iv-ii'
      - name: Output time set in container
        run: echo 'Container action start time - ${{ steps.hello-action-outputs.time }}'
